/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JComponent;

/**
 *
 * @author jroge
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    List<JComponent> components;
    
    public Main() {
        initComponents();
        this.setSize(700, 500);
        addAllMyComponents();
        setVisibleAllComponents(false);
        btn.setVisible(true);
        setOriginalName();
    }
    
    private void addAllMyComponents() {
        //Button, Toggle Button, Check Box, Radio Button,
        //Button Group, Text Field, Text Area,
        //Slider, Password Field, Spinner
        components = new LinkedList<>();
        components.add(btn);
        components.add(tglBtn);
        components.forEach((component) -> {
            component.setBackground(Color.decode("#aaaaa9"));
        });
    }
    
    private void setVisibleAllComponents(boolean state) {
        components.forEach((component) -> {
            component.setVisible(state);
        });
    }
    
    private void setOriginalName() {
        switch (elements.getSelectedIndex()) {
            case 0: {
                btn.setText("JButton");
            }
            case 1: {
                tglBtn.setText("JToggleButton");
            }
        }
    }
    
    private void changeSize() {
        components.get(elements.getSelectedIndex()).setSize(
                (int) (((368 * spinner.getValue()) / 100) + 92),
                (int) (((104 * spinner.getValue()) / 100) + 26));
        components.get(elements.getSelectedIndex()).setLocation(
                130 - ((120 * spinner.getValue()) / 100),
                39 - ((29 * spinner.getValue()) / 100));
    }
    
    private void changeColor() {
        System.out.println(components.get(0).getColorModel());
        Color[] myColors = {Color.decode("#aaaaa9"), Color.RED, Color.BLUE, Color.GREEN, Color.YELLOW};
        components.get(elements.getSelectedIndex()).setBackground(myColors[colors.getSelectedIndex()]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elements = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        tglBtn = new javax.swing.JToggleButton();
        btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        setOriginalName = new javax.swing.JButton();
        setThisName = new javax.swing.JButton();
        newName = new javax.swing.JTextField();
        spinner = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        colors = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(9, 78, 135));
        getContentPane().setLayout(null);

        elements.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Button", "Toggle Button", "Check Box", "Radio Button", "Button Group", "Text Field", "Text Area", "Slider", "Password Field", "Spinner" }));
        elements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elementsActionPerformed(evt);
            }
        });
        getContentPane().add(elements);
        elements.setBounds(12, 67, 177, 36);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        tglBtn.setText("jToggleButton1");

        btn.setText("jButton1");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(195, 67, 485, 149);

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(null);

        setOriginalName.setText("Set Original Name");
        setOriginalName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setOriginalNameActionPerformed(evt);
            }
        });
        jPanel2.add(setOriginalName);
        setOriginalName.setBounds(12, 12, 131, 29);

        setThisName.setText("Set This Name:");
        setThisName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setThisNameActionPerformed(evt);
            }
        });
        jPanel2.add(setThisName);
        setThisName.setBounds(12, 59, 131, 29);
        jPanel2.add(newName);
        newName.setBounds(12, 100, 131, 36);

        spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerStateChanged(evt);
            }
        });
        jPanel2.add(spinner);
        spinner.setBounds(250, 0, 133, 51);

        jLabel1.setText("Change Size");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(161, 17, 90, 19);

        jLabel2.setText("Change Color");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(160, 70, 100, 19);

        colors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Red", "Blue", "Green", "Yellow" }));
        colors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorsActionPerformed(evt);
            }
        });
        jPanel2.add(colors);
        colors.setBounds(260, 60, 120, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 230, 670, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elementsActionPerformed
        setVisibleAllComponents(false);
        setOriginalName();
        components.get(elements.getSelectedIndex()).setVisible(true);
    }//GEN-LAST:event_elementsActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        btn.setText("Button Clicked!");
    }//GEN-LAST:event_btnActionPerformed

    private void setOriginalNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setOriginalNameActionPerformed
        setOriginalName();
    }//GEN-LAST:event_setOriginalNameActionPerformed

    private void setThisNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setThisNameActionPerformed
        switch (elements.getSelectedIndex()) {
            case 0: {
                btn.setText(newName.getText());
            }
            case 1: {
                tglBtn.setText(newName.getText());
            }
        }
    }//GEN-LAST:event_setThisNameActionPerformed

    private void spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerStateChanged
        changeSize();
    }//GEN-LAST:event_spinnerStateChanged

    private void colorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorsActionPerformed
        changeColor();
    }//GEN-LAST:event_colorsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JComboBox<String> colors;
    private javax.swing.JComboBox<String> elements;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField newName;
    private javax.swing.JButton setOriginalName;
    private javax.swing.JButton setThisName;
    private javax.swing.JSlider spinner;
    private javax.swing.JToggleButton tglBtn;
    // End of variables declaration//GEN-END:variables
}
